/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practical_4;

/**
 *
 * @author shalmon
 */
public class question_3 extends java.awt.Frame {

    /**
     * Creates new form question_3
     */
    public question_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label4 = new java.awt.Label();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        button1 = new java.awt.Button();
        label5 = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setName(""); // NOI18N
        label1.setText("Name:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, -1));

        label2.setText("Student Details:");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        label3.setText("Contact Number:");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, -1));

        label4.setText("Course Offered:");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        checkbox1.setLabel("Bioinformatics");
        add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        checkbox2.setLabel("Botany");
        add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        checkbox3.setLabel("Biochemistry");
        add(checkbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        button1.setLabel("SUBMIT");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        label5.setText("Successfull!!!");
        label5.setVisible(false);
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if(textField1.getText().length() > 0 && textField2.getText().length() > 0){
            label5.setText("Successfull!!");
            label5.setVisible(true);
        }
        else{
            label5.setText("Enter Details!!");
            label5.setVisible(true);
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question_3().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
