/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practical_4;

/**
 *
 * @author nasha
 */
public class question_4 extends java.awt.Frame {

    /**
     * Creates new form question_4
     */
    public question_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();

        setBackground(java.awt.Color.blue);
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textField1.setForeground(new java.awt.Color(255, 0, 0));
        textField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textField1MouseExited(evt);
            }
        });
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseEntered
        textField1.setText("Mouse Entered");
    }//GEN-LAST:event_textField1MouseEntered

    private void textField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseExited
        textField1.setText("Mouse Exited");
    }//GEN-LAST:event_textField1MouseExited

    private void textField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseClicked
        textField1.setText("Mouse Clicked");
    }//GEN-LAST:event_textField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question_4().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
