/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package awt_lecture_code;

/**
 *
 * @author nasha
 */
public class food_order extends java.awt.Frame {

    /**
     * Creates new form food_order
     */
    public food_order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new java.awt.Label();
        cb1 = new java.awt.Checkbox();
        cb2 = new java.awt.Checkbox();
        cb3 = new java.awt.Checkbox();
        cb4 = new java.awt.Checkbox();
        order = new java.awt.Button();
        order_label = new java.awt.Label();

        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setAlignment(java.awt.Label.CENTER);
        Title.setText("What item would you like to eat?");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 40));

        cb1.setLabel("Pizza");
        add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, -1));

        cb2.setLabel("Burger");
        add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 80, 100, -1));

        cb3.setLabel("Fries");
        add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, -1));

        cb4.setLabel("Noodles");
        add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 130, 100, -1));

        order.setLabel("ORDER");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 50));

        order_label.setAlignment(java.awt.Label.CENTER);
        add(order_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 250, 380, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
   
    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        String order[] = new String[3];
        String order_print = "";
        order[0] = "Pizza";
        order[1] = "Burger";
        order[2] = "Fries";
        order[3] = "Noodles";
        if(cb1.getState() == true){
            order[0] = "Pizza";
        }
        if(cb2.getState() == true){
            order[1] = "Burger";
        }
        if(cb3.getState() == true){
            order[2] = "Fries";
        }
        if(cb4.getState() == true){
            order[3] = "Noodles";
        }
        
        for(int i=0; i<3; i++){
            order_print.concat(order[i]);
        }
        order_label.setText(order_print);
        
    }//GEN-LAST:event_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new food_order().setVisible(true);
            }
        });
        
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Title;
    private java.awt.Checkbox cb1;
    private java.awt.Checkbox cb2;
    private java.awt.Checkbox cb3;
    private java.awt.Checkbox cb4;
    private java.awt.Button order;
    private java.awt.Label order_label;
    // End of variables declaration//GEN-END:variables
}
